/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EponIndexRouteImport } from './routes/epon/index'
import { Route as BroadbandIndexRouteImport } from './routes/broadband/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EponIndexRoute = EponIndexRouteImport.update({
  id: '/epon/',
  path: '/epon/',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadbandIndexRoute = BroadbandIndexRouteImport.update({
  id: '/broadband/',
  path: '/broadband/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/broadband': typeof BroadbandIndexRoute
  '/epon': typeof EponIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/broadband': typeof BroadbandIndexRoute
  '/epon': typeof EponIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/broadband/': typeof BroadbandIndexRoute
  '/epon/': typeof EponIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/broadband' | '/epon'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/broadband' | '/epon'
  id: '__root__' | '/' | '/broadband/' | '/epon/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BroadbandIndexRoute: typeof BroadbandIndexRoute
  EponIndexRoute: typeof EponIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epon/': {
      id: '/epon/'
      path: '/epon'
      fullPath: '/epon'
      preLoaderRoute: typeof EponIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadband/': {
      id: '/broadband/'
      path: '/broadband'
      fullPath: '/broadband'
      preLoaderRoute: typeof BroadbandIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BroadbandIndexRoute: BroadbandIndexRoute,
  EponIndexRoute: EponIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
