/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OcrIndexRouteImport } from './routes/ocr/index'
import { Route as LogsIndexRouteImport } from './routes/logs/index'
import { Route as LogKomplainIndexRouteImport } from './routes/log-komplain/index'
import { Route as LauncerIndexRouteImport } from './routes/launcer/index'
import { Route as EponIndexRouteImport } from './routes/epon/index'
import { Route as BroadbandIndexRouteImport } from './routes/broadband/index'
import { Route as OcrComponentsResultDisplayRouteImport } from './routes/ocr/components/resultDisplay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OcrIndexRoute = OcrIndexRouteImport.update({
  id: '/ocr/',
  path: '/ocr/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIndexRoute = LogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogKomplainIndexRoute = LogKomplainIndexRouteImport.update({
  id: '/log-komplain/',
  path: '/log-komplain/',
  getParentRoute: () => rootRouteImport,
} as any)
const LauncerIndexRoute = LauncerIndexRouteImport.update({
  id: '/launcer/',
  path: '/launcer/',
  getParentRoute: () => rootRouteImport,
} as any)
const EponIndexRoute = EponIndexRouteImport.update({
  id: '/epon/',
  path: '/epon/',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadbandIndexRoute = BroadbandIndexRouteImport.update({
  id: '/broadband/',
  path: '/broadband/',
  getParentRoute: () => rootRouteImport,
} as any)
const OcrComponentsResultDisplayRoute =
  OcrComponentsResultDisplayRouteImport.update({
    id: '/ocr/components/resultDisplay',
    path: '/ocr/components/resultDisplay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/broadband': typeof BroadbandIndexRoute
  '/epon': typeof EponIndexRoute
  '/launcer': typeof LauncerIndexRoute
  '/log-komplain': typeof LogKomplainIndexRoute
  '/logs': typeof LogsIndexRoute
  '/ocr': typeof OcrIndexRoute
  '/ocr/components/resultDisplay': typeof OcrComponentsResultDisplayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/broadband': typeof BroadbandIndexRoute
  '/epon': typeof EponIndexRoute
  '/launcer': typeof LauncerIndexRoute
  '/log-komplain': typeof LogKomplainIndexRoute
  '/logs': typeof LogsIndexRoute
  '/ocr': typeof OcrIndexRoute
  '/ocr/components/resultDisplay': typeof OcrComponentsResultDisplayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/broadband/': typeof BroadbandIndexRoute
  '/epon/': typeof EponIndexRoute
  '/launcer/': typeof LauncerIndexRoute
  '/log-komplain/': typeof LogKomplainIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/ocr/': typeof OcrIndexRoute
  '/ocr/components/resultDisplay': typeof OcrComponentsResultDisplayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/broadband'
    | '/epon'
    | '/launcer'
    | '/log-komplain'
    | '/logs'
    | '/ocr'
    | '/ocr/components/resultDisplay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/broadband'
    | '/epon'
    | '/launcer'
    | '/log-komplain'
    | '/logs'
    | '/ocr'
    | '/ocr/components/resultDisplay'
  id:
    | '__root__'
    | '/'
    | '/broadband/'
    | '/epon/'
    | '/launcer/'
    | '/log-komplain/'
    | '/logs/'
    | '/ocr/'
    | '/ocr/components/resultDisplay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BroadbandIndexRoute: typeof BroadbandIndexRoute
  EponIndexRoute: typeof EponIndexRoute
  LauncerIndexRoute: typeof LauncerIndexRoute
  LogKomplainIndexRoute: typeof LogKomplainIndexRoute
  LogsIndexRoute: typeof LogsIndexRoute
  OcrIndexRoute: typeof OcrIndexRoute
  OcrComponentsResultDisplayRoute: typeof OcrComponentsResultDisplayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr/': {
      id: '/ocr/'
      path: '/ocr'
      fullPath: '/ocr'
      preLoaderRoute: typeof OcrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/': {
      id: '/logs/'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-komplain/': {
      id: '/log-komplain/'
      path: '/log-komplain'
      fullPath: '/log-komplain'
      preLoaderRoute: typeof LogKomplainIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launcer/': {
      id: '/launcer/'
      path: '/launcer'
      fullPath: '/launcer'
      preLoaderRoute: typeof LauncerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epon/': {
      id: '/epon/'
      path: '/epon'
      fullPath: '/epon'
      preLoaderRoute: typeof EponIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadband/': {
      id: '/broadband/'
      path: '/broadband'
      fullPath: '/broadband'
      preLoaderRoute: typeof BroadbandIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr/components/resultDisplay': {
      id: '/ocr/components/resultDisplay'
      path: '/ocr/components/resultDisplay'
      fullPath: '/ocr/components/resultDisplay'
      preLoaderRoute: typeof OcrComponentsResultDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BroadbandIndexRoute: BroadbandIndexRoute,
  EponIndexRoute: EponIndexRoute,
  LauncerIndexRoute: LauncerIndexRoute,
  LogKomplainIndexRoute: LogKomplainIndexRoute,
  LogsIndexRoute: LogsIndexRoute,
  OcrIndexRoute: OcrIndexRoute,
  OcrComponentsResultDisplayRoute: OcrComponentsResultDisplayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
